### ISSUE TITLE
[ADD] Ajouter la traduction du Score de collection

### ISSUE THREAD

**Issue by dokor** [ruleslabs/interface#7]
Hello Charles, 

Il manque le wording de traduction FR de la clé "Collection score: {fullParsedCScore}". 
Ce wording est présent dans la pop-in du composant src/components/Homepage/HallOfFame/UserRow.tsx

Afin de corriger cette issue, il faut ajouter : 

`#: src/components/Homepage/HallOfFame/UserRow.tsx`
`msgid "Collection score: {fullParsedCScore}"`
`msgstr "Score de collection : {fullParsedCScore}"`

sous la ligne 1377 du fichier /src/locales/fr-FR.po
https://github.com/ruleslabs/interface/blob/d765ea1b31bd3d75cdf90819dd1e7fe5149dbfc8/src/locales/fr-FR.po#L1377

Bonne journée,

**Comment by 0xChqrles** [comment]
Salut ! Merci, c'est fixé 👌
